sudo: false
language: generic
matrix:
  include:
    - os: linux
      language: python
      python: "3.4"
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      language: python
      python: "3.6-dev"
    - os: linux
      language: python
      python: "3.7-dev"
    - os: linux
      language: python
      python: "pypy3.5-5.7.1-beta"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.4.6"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5.3"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6.2"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6-dev"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7-dev"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="pypy3.5-5.8.0-src"
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - env: TRAVIS_PYTHON_VERSION="3.6-dev"
    - env: TRAVIS_PYTHON_VERSION="3.7-dev"

before_install: |
  set -e
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew update
    brew install pyenv || brew upgrade pyenv
    pyenv install --list
    pyenv install "${TRAVIS_PYTHON_VERSION}"
    export PATH="$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:${PATH}"
  fi
  set +e

install:
  - pip install -U pip
  - pip install -U -r dev_requirements.txt

script:
  - TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest discover --verbose

after_success:
  - python -m coverage report --show-missing
  - coveralls
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")

notifications:
  slack:
    secure: "m10wMO0tqsggvtlJ+jdbQJQSfij/pa2nlr6LQsiAHUENeydVSa0ZejHjPRwbIoVYi+VXe3WAON6K4fKziBahEv92Z3PokGEnCE3AiAwXHM2F2dNuJqeug0UW7VZcEMAXK+yUW2ZTlJUTVDZg4A8EVCbV5lJ1cR61XisVEtk/DmC9lyms1UXNerUCImPlGwk6c0NbXYieZdMV1qljvuqZWjC8ZhgLle44NHPptDgltlRha9Qh+mh0CpoF4zTfXmSD0T2RLUygJ0iawL1fTmpxjn0QvbIo99KHkXwHir08S8zwjPwcBqm8cNue+BUfmnJFZbY31uOdhhYMKNTJu+pcdsN/6WfezKvDS/uLiOk0QCtZRm9oaSQxCh/wGgPIlTCO2Ui5RuK9iWo8rc6Kn0kdu2roCWwdV1sBiDbcJ4CPQoyadSVSqJTQswNwxUytDtAnlygcAwEiTREMoe3gyO5bSv0W29K2chL3cbBmaTQ+F6TuOPxVBkaezgRO7IMN52tht14obcLMuByccDVkUKJ2pG8rwgdwPZ8I6gcYdP0KgQs9d8Q5PMSaiwM8o/zmGTfvQqcbyCKaswwiAJEpq5g6rNsaXL2c9BV7CLMGBouy2UFPckqtC+4AnLWj6hiGYQGdidKzZ/eCjOG3W/HY/H/GPdvwPBx43jFURk8ZdKJBrVs="
  email: false
