sudo: false
language: generic
matrix:
  include:
    - os: linux
      language: python
      python: "3.4"
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
    - os: linux
      dist: xenial
      sudo: true
      language: python
      python: "3.7"
    - os: linux
      language: python
      python: "3.8-dev"
    - os: linux
      language: python
      python: "pypy3.5-5.8.0"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.4.8"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.5.5"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.6.6"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.7.0"
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION="3.8-dev"
  allow_failures:
    - python: "3.8-dev"
    - env: TRAVIS_PYTHON_VERSION="3.8-dev"

before_install: |
  set -e
  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
    brew update
    brew install pyenv || brew upgrade pyenv
    pyenv install --list
    pyenv install "${TRAVIS_PYTHON_VERSION}"
    export PATH="$HOME/.pyenv/versions/${TRAVIS_PYTHON_VERSION}/bin:${PATH}"
  fi
  set +e

install:
  - pip install -U pip
  - pip install -U -r dev_requirements.txt
  # just some example Python packages
  - git clone https://github.com/PyCQA/pylint ../pylint
  - cd ../pylint && python setup.py build && cd -
  - git clone https://github.com/mbdevpl/argunparse ../argunparse
  - cd ../argunparse && pip install -r test_requirements.txt && python setup.py build && cd -
  - git clone https://github.com/k-bx/python-semver ../semver
  - cd ../semver && python setup.py build && cd -

script:
  - TEST_PACKAGING=1 python -m coverage run --branch --source . -m unittest -v
  - LOGGING_LEVEL=critical python -m coverage run --append --branch --source . -m unittest -v test.test_version

after_success:
  - python -m coverage report --show-missing
  - codecov

before_deploy:
  - pip3 install -U --user version_query || pip3 install -U version_query
  - wget https://gist.githubusercontent.com/mbdevpl/46d458350f0c9cc7d793b67573e01f7b/raw/prepare_bintray_deployment.py
  - python3 prepare_bintray_deployment.py "$TRAVIS_OS_NAME-python$TRAVIS_PYTHON_VERSION" "dist/*.tar.gz" "dist/*.whl" "dist/*.zip"

deploy:
  - provider: bintray
    file: ".bintray.json"
    user: "mbdevpl"
    key:
      secure: "nCFnq4OedRxTWRk0mgZP0PJiFVRsNQXV2kII2EEq2fMz64I4R4PrHf+oWUYt5P+64H4OFE+IqDFMJfb0S1Dgt2IF480+Hz1t+jWDzeyhbzBIa4XkbnhkDH6ChgTW/Mv/rijjgvXBrBoUhFKqGphJ8SAIVISd2KSB5ciEoWnyJ8nyy6sXxOKFbxMXYaTIkDazRZdNzvQJ+6p9KwbEYnOG4cRddklvejn4iWFKKVcfZEtnkY0cMEUdmHjmr6kJqF2S5XhFZ8I6n0cVfu12ja2kMrJY2ljWiqjnUUTBEyAKPvOXYlMdfXo3edEUE+FmCKUMNNo21Dv/4hoM978tIiu5P4jbd9NIqULncIyPvSq/kbV/2CG9xSCwl9OL7uTvZqaoe/QpUX140cO60jkkDf0YqXpk0sGuXIE+xfYNMRsH+BzSmDD+TGadJD63GrdNOPPyEDW+NKSis3DzMLiAdVOYstoIUdd07DW+4tS7JKzMzOdruUOve6Uq+PvwNObcTi3vZrOl98NIu6DTYyXTe/sb2If8WBpnmkfl8Ua/Q0KjcLLONiespxJxtMfyuFiN5l+tFIC3pWGK5+QA9DnM5FTkdXwkbqGdqmvK17ponHgKhjjr8YVGVYoXu4G+2mRhWWCPe5PFQbPQtM2br4j+wCugmPL1qkfFXcJ6Oavjqxpg7y8="
    on:
      all_branches: true
    skip_cleanup: true

notifications:
  slack:
    secure: "m10wMO0tqsggvtlJ+jdbQJQSfij/pa2nlr6LQsiAHUENeydVSa0ZejHjPRwbIoVYi+VXe3WAON6K4fKziBahEv92Z3PokGEnCE3AiAwXHM2F2dNuJqeug0UW7VZcEMAXK+yUW2ZTlJUTVDZg4A8EVCbV5lJ1cR61XisVEtk/DmC9lyms1UXNerUCImPlGwk6c0NbXYieZdMV1qljvuqZWjC8ZhgLle44NHPptDgltlRha9Qh+mh0CpoF4zTfXmSD0T2RLUygJ0iawL1fTmpxjn0QvbIo99KHkXwHir08S8zwjPwcBqm8cNue+BUfmnJFZbY31uOdhhYMKNTJu+pcdsN/6WfezKvDS/uLiOk0QCtZRm9oaSQxCh/wGgPIlTCO2Ui5RuK9iWo8rc6Kn0kdu2roCWwdV1sBiDbcJ4CPQoyadSVSqJTQswNwxUytDtAnlygcAwEiTREMoe3gyO5bSv0W29K2chL3cbBmaTQ+F6TuOPxVBkaezgRO7IMN52tht14obcLMuByccDVkUKJ2pG8rwgdwPZ8I6gcYdP0KgQs9d8Q5PMSaiwM8o/zmGTfvQqcbyCKaswwiAJEpq5g6rNsaXL2c9BV7CLMGBouy2UFPckqtC+4AnLWj6hiGYQGdidKzZ/eCjOG3W/HY/H/GPdvwPBx43jFURk8ZdKJBrVs="
  email: false
